server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://moine.ctmozwzrav97.ap-northeast-2.rds.amazonaws.com:3306/Group?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Moine18!
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
  #  jpa:
  #    properties:
  #      hibernate:
  #        show_sql: true
  #        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Group
          destination: moine
          contentType: application/json
        event-out:
          destination: moine
          contentType: application/json

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8082
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Group
          destination: moine
          contentType: application/json
        event-out:
          destination: moine
          contentType: application/json