apiVersion: v1
kind: Service
metadata:
  name: group-backend-svc
  labels:
    app: group-backend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: group
      protocol: TCP
      targetPort: 8080
  selector:
    app: group
